version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEFAULT_REGION=eu-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./scripts/localstack-init.sh:/etc/localstack/init/ready.d/init.sh"
      - "localstack-data:/var/lib/localstack"

volumes:
  localstack-data:
